name: Check Markdown links

on:
  schedule:
    - cron: "0 9 * * *"
  push:
    branches:
      - main
  pull_request: {}

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
